from setuptools import setup

setup(
    name='HackeRank',
    version='',
    packages=['test', 'code3', 'code3.lib', 'code3.lib.python3.9', 'code3.lib.python3.9.site-packages',
              'code3.lib.python3.9.site-packages.bs4', 'code3.lib.python3.9.site-packages.bs4.tests',
              'code3.lib.python3.9.site-packages.bs4.builder', 'code3.lib.python3.9.site-packages.pip',
              'code3.lib.python3.9.site-packages.pip._vendor', 'code3.lib.python3.9.site-packages.pip._vendor.idna',
              'code3.lib.python3.9.site-packages.pip._vendor.toml',
              'code3.lib.python3.9.site-packages.pip._vendor.pep517',
              'code3.lib.python3.9.site-packages.pip._vendor.pep517.in_process',
              'code3.lib.python3.9.site-packages.pip._vendor.certifi',
              'code3.lib.python3.9.site-packages.pip._vendor.chardet',
              'code3.lib.python3.9.site-packages.pip._vendor.chardet.cli',
              'code3.lib.python3.9.site-packages.pip._vendor.chardet.metadata',
              'code3.lib.python3.9.site-packages.pip._vendor.distlib',
              'code3.lib.python3.9.site-packages.pip._vendor.distlib._backport',
              'code3.lib.python3.9.site-packages.pip._vendor.msgpack',
              'code3.lib.python3.9.site-packages.pip._vendor.urllib3',
              'code3.lib.python3.9.site-packages.pip._vendor.urllib3.util',
              'code3.lib.python3.9.site-packages.pip._vendor.urllib3.contrib',
              'code3.lib.python3.9.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'code3.lib.python3.9.site-packages.pip._vendor.urllib3.packages',
              'code3.lib.python3.9.site-packages.pip._vendor.urllib3.packages.backports',
              'code3.lib.python3.9.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'code3.lib.python3.9.site-packages.pip._vendor.colorama',
              'code3.lib.python3.9.site-packages.pip._vendor.html5lib',
              'code3.lib.python3.9.site-packages.pip._vendor.html5lib._trie',
              'code3.lib.python3.9.site-packages.pip._vendor.html5lib.filters',
              'code3.lib.python3.9.site-packages.pip._vendor.html5lib.treewalkers',
              'code3.lib.python3.9.site-packages.pip._vendor.html5lib.treeadapters',
              'code3.lib.python3.9.site-packages.pip._vendor.html5lib.treebuilders',
              'code3.lib.python3.9.site-packages.pip._vendor.progress',
              'code3.lib.python3.9.site-packages.pip._vendor.requests',
              'code3.lib.python3.9.site-packages.pip._vendor.tenacity',
              'code3.lib.python3.9.site-packages.pip._vendor.packaging',
              'code3.lib.python3.9.site-packages.pip._vendor.resolvelib',
              'code3.lib.python3.9.site-packages.pip._vendor.resolvelib.compat',
              'code3.lib.python3.9.site-packages.pip._vendor.cachecontrol',
              'code3.lib.python3.9.site-packages.pip._vendor.cachecontrol.caches',
              'code3.lib.python3.9.site-packages.pip._vendor.webencodings',
              'code3.lib.python3.9.site-packages.pip._vendor.pkg_resources',
              'code3.lib.python3.9.site-packages.pip._internal', 'code3.lib.python3.9.site-packages.pip._internal.cli',
              'code3.lib.python3.9.site-packages.pip._internal.req',
              'code3.lib.python3.9.site-packages.pip._internal.vcs',
              'code3.lib.python3.9.site-packages.pip._internal.index',
              'code3.lib.python3.9.site-packages.pip._internal.utils',
              'code3.lib.python3.9.site-packages.pip._internal.models',
              'code3.lib.python3.9.site-packages.pip._internal.network',
              'code3.lib.python3.9.site-packages.pip._internal.commands',
              'code3.lib.python3.9.site-packages.pip._internal.metadata',
              'code3.lib.python3.9.site-packages.pip._internal.locations',
              'code3.lib.python3.9.site-packages.pip._internal.operations',
              'code3.lib.python3.9.site-packages.pip._internal.operations.build',
              'code3.lib.python3.9.site-packages.pip._internal.operations.install',
              'code3.lib.python3.9.site-packages.pip._internal.resolution',
              'code3.lib.python3.9.site-packages.pip._internal.resolution.legacy',
              'code3.lib.python3.9.site-packages.pip._internal.resolution.resolvelib',
              'code3.lib.python3.9.site-packages.pip._internal.distributions',
              'code3.lib.python3.9.site-packages.soupsieve', 'code3.lib.python3.9.site-packages.setuptools',
              'code3.lib.python3.9.site-packages.setuptools.extern',
              'code3.lib.python3.9.site-packages.setuptools._vendor',
              'code3.lib.python3.9.site-packages.setuptools._vendor.packaging',
              'code3.lib.python3.9.site-packages.setuptools._vendor.more_itertools',
              'code3.lib.python3.9.site-packages.setuptools.command',
              'code3.lib.python3.9.site-packages.setuptools._distutils',
              'code3.lib.python3.9.site-packages.setuptools._distutils.command',
              'code3.lib.python3.9.site-packages.pkg_resources',
              'code3.lib.python3.9.site-packages.pkg_resources.extern',
              'code3.lib.python3.9.site-packages.pkg_resources._vendor',
              'code3.lib.python3.9.site-packages.pkg_resources._vendor.packaging',
              'code3.lib.python3.9.site-packages._distutils_hack'],
    url='',
    license='',
    author='aishwaryashukla',
    author_email='',
    description=''
)
